package com.mds.manager.dao;

import com.mds.manager.model.Email;
import com.mds.manager.model.EmailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    int countByExample(EmailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    int deleteByExample(EmailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    int insert(Email record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    int insertSelective(Email record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    List<Email> selectByExample(EmailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    Email selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    int updateByExampleSelective(@Param("record") Email record, @Param("example") EmailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    int updateByExample(@Param("record") Email record, @Param("example") EmailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    int updateByPrimaryKeySelective(Email record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    int updateByPrimaryKey(Email record);
    
    /**
     * 分页数据
     * @param start
     * @param pageNum
     * @param example
     * @return
     */
    List<Email> getEmailPages(@Param("start") int start, @Param("pageNum") int pageNum,  @Param("example")EmailExample example);
}