package com.mds.manager.dao;

import com.mds.manager.model.Notice;
import com.mds.manager.model.NoticeExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface NoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    int countByExample(NoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    int deleteByExample(NoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    int insert(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    int insertSelective(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    List<Notice> selectByExample(NoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    Notice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    int updateByExampleSelective(@Param("record") Notice record, @Param("example") NoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    int updateByExample(@Param("record") Notice record, @Param("example") NoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    int updateByPrimaryKeySelective(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    int updateByPrimaryKey(Notice record);
    
    /**
     * 获取分页数据
     * @param start
     * @param pageNum
     * @param example
     * @return
     */
    List<Notice> getNoticePages(@Param("start") int start, @Param("pageNum") int pageNum,  @Param("example")NoticeExample example);
    
    /**
     * 批量删除系统公告
     * @param ids
     * @return
     */
    int batchDelNotice(String[] ids);
}