package com.mds.manager.dao;

import com.mds.manager.model.Organization;
import com.mds.manager.model.OrganizationExample;
import com.mds.manager.model.Tree;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface OrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    int countByExample(OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    int deleteByExample(OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    int insert(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    int insertSelective(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    List<Organization> selectByExample(OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    Organization selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    int updateByExampleSelective(@Param("record") Organization record, @Param("example") OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    int updateByExample(@Param("record") Organization record, @Param("example") OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    int updateByPrimaryKeySelective(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    int updateByPrimaryKey(Organization record);
    
    /**
     * 获取树形结构
     * @param organization
     * @return
     */
    List<Tree> selectTreeNodes(String organization);
    
    /**
     * 根据树节点ID获取当前节点和父节点信息
     * @param organization
     * @return
     */
    Map<String, Object> selectParentNodeInfoById(Long id);
}