package com.mds.manager.dao;

import com.mds.manager.model.RoleUser;
import com.mds.manager.model.RoleUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_user
     *
     * @mbggenerated Sat Aug 26 18:34:51 CST 2017
     */
    int countByExample(RoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_user
     *
     * @mbggenerated Sat Aug 26 18:34:51 CST 2017
     */
    int deleteByExample(RoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_user
     *
     * @mbggenerated Sat Aug 26 18:34:51 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_user
     *
     * @mbggenerated Sat Aug 26 18:34:51 CST 2017
     */
    int insert(RoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_user
     *
     * @mbggenerated Sat Aug 26 18:34:51 CST 2017
     */
    int insertSelective(RoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_user
     *
     * @mbggenerated Sat Aug 26 18:34:51 CST 2017
     */
    List<RoleUser> selectByExample(RoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_user
     *
     * @mbggenerated Sat Aug 26 18:34:51 CST 2017
     */
    RoleUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_user
     *
     * @mbggenerated Sat Aug 26 18:34:51 CST 2017
     */
    int updateByExampleSelective(@Param("record") RoleUser record, @Param("example") RoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_user
     *
     * @mbggenerated Sat Aug 26 18:34:51 CST 2017
     */
    int updateByExample(@Param("record") RoleUser record, @Param("example") RoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_user
     *
     * @mbggenerated Sat Aug 26 18:34:51 CST 2017
     */
    int updateByPrimaryKeySelective(RoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_user
     *
     * @mbggenerated Sat Aug 26 18:34:51 CST 2017
     */
    int updateByPrimaryKey(RoleUser record);
    
    /**
     * 批量插入
     * @param list
     * @return
     */
    int batchInsert(List<RoleUser> list);
}