package com.mds.manager.dao;

import com.mds.manager.model.Sms;
import com.mds.manager.model.SmsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    int countByExample(SmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    int deleteByExample(SmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    int insert(Sms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    int insertSelective(Sms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    List<Sms> selectByExample(SmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    Sms selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    int updateByExampleSelective(@Param("record") Sms record, @Param("example") SmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    int updateByExample(@Param("record") Sms record, @Param("example") SmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    int updateByPrimaryKeySelective(Sms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    int updateByPrimaryKey(Sms record);
    
    /**
     * 分页数据
     * @param start
     * @param pageNum
     * @param example
     * @return
     */
    List<Sms> getSmsPages(@Param("start") int start, @Param("pageNum") int pageNum,  @Param("example")SmsExample example);

    List<Sms> getCheckVerifyCode(@Param("phone")String phone ,@Param("minus") Integer minus);
}