package com.mds.manager.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.mds.manager.model.SysResource;
import com.mds.manager.model.SysResourceExample;

public interface SysResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    int countByExample(SysResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    int deleteByExample(SysResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    int insert(SysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    int insertSelective(SysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    List<SysResource> selectByExample(SysResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    SysResource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    int updateByExampleSelective(@Param("record") SysResource record, @Param("example") SysResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    int updateByExample(@Param("record") SysResource record, @Param("example") SysResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    int updateByPrimaryKeySelective(SysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    int updateByPrimaryKey(SysResource record);
    
    /**
     * 获取分页数据
     * @param Page
     * @return
     */
    List<SysResource> getResourcePage(@Param("start") int start, @Param("pageNum") int pageNum,  @Param("example")SysResourceExample example);
    
    /**
     * 批量删除用户
     * @param ids
     * @return
     */
    int batchDelResource(String[] ids);
}