package com.mds.manager.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.mds.manager.model.SysResource;
import com.mds.manager.model.User;
import com.mds.manager.model.UserExample;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Aug 16 11:49:52 CST 2017
     */
    int countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Aug 16 11:49:52 CST 2017
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Aug 16 11:49:52 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Aug 16 11:49:52 CST 2017
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Aug 16 11:49:52 CST 2017
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Aug 16 11:49:52 CST 2017
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Aug 16 11:49:52 CST 2017
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Aug 16 11:49:52 CST 2017
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Aug 16 11:49:52 CST 2017
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Aug 16 11:49:52 CST 2017
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Aug 16 11:49:52 CST 2017
     */
    int updateByPrimaryKey(User record);
    
    /**
     * 根据用户id查询所有的权限资源
     * @param uid
     * @return
     */
    List<SysResource> listAllResources(Long uid);
    
    /**
     * 根据用户id查询用户所有角色
     * @param uid
     * @return
     */
    List<String> listRoleSnByUser(Long uid);
    
    /**
     * 获取用户分页数据
     * @param start
     * @param pageNum
     * @param
     * @return
     */
    List<User> getUserPages(@Param("start") int start, @Param("pageNum") int pageNum,  @Param("example")UserExample example);
    
    /**
     * 根据id批量删除用户
     * @param ids：1,2,3		以逗号间隔的字符串
     * @return
     */
    int batchDelUser(String[] ids);
    
    /**
     * 获取未绑定用户
     * @return
     */
    List<User> getNoBindingUser(String roleId);
}