package com.mds.manager.model;

import java.util.Date;

public class Email {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_email.id
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_email.system_no
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    private Boolean systemNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_email.email_no
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    private String emailNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_email.email_to
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    private String emailTo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_email.email_touser
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    private String emailTouser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_email.email_carboncopy
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    private String emailCarboncopy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_email.email_title
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    private String emailTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_email.email_content
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    private String emailContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_email.email_from
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    private String emailFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_email.email_fromuser
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    private String emailFromuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_email.create_time
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_email.send_time
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_email.email_status
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    private Integer emailStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_email.id
     *
     * @return the value of t_email.id
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_email.id
     *
     * @param id the value for t_email.id
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_email.system_no
     *
     * @return the value of t_email.system_no
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public Boolean getSystemNo() {
        return systemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_email.system_no
     *
     * @param systemNo the value for t_email.system_no
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public void setSystemNo(Boolean systemNo) {
        this.systemNo = systemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_email.email_no
     *
     * @return the value of t_email.email_no
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public String getEmailNo() {
        return emailNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_email.email_no
     *
     * @param emailNo the value for t_email.email_no
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public void setEmailNo(String emailNo) {
        this.emailNo = emailNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_email.email_to
     *
     * @return the value of t_email.email_to
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public String getEmailTo() {
        return emailTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_email.email_to
     *
     * @param emailTo the value for t_email.email_to
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public void setEmailTo(String emailTo) {
        this.emailTo = emailTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_email.email_touser
     *
     * @return the value of t_email.email_touser
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public String getEmailTouser() {
        return emailTouser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_email.email_touser
     *
     * @param emailTouser the value for t_email.email_touser
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public void setEmailTouser(String emailTouser) {
        this.emailTouser = emailTouser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_email.email_carboncopy
     *
     * @return the value of t_email.email_carboncopy
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public String getEmailCarboncopy() {
        return emailCarboncopy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_email.email_carboncopy
     *
     * @param emailCarboncopy the value for t_email.email_carboncopy
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public void setEmailCarboncopy(String emailCarboncopy) {
        this.emailCarboncopy = emailCarboncopy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_email.email_title
     *
     * @return the value of t_email.email_title
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public String getEmailTitle() {
        return emailTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_email.email_title
     *
     * @param emailTitle the value for t_email.email_title
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public void setEmailTitle(String emailTitle) {
        this.emailTitle = emailTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_email.email_content
     *
     * @return the value of t_email.email_content
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public String getEmailContent() {
        return emailContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_email.email_content
     *
     * @param emailContent the value for t_email.email_content
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public void setEmailContent(String emailContent) {
        this.emailContent = emailContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_email.email_from
     *
     * @return the value of t_email.email_from
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public String getEmailFrom() {
        return emailFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_email.email_from
     *
     * @param emailFrom the value for t_email.email_from
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public void setEmailFrom(String emailFrom) {
        this.emailFrom = emailFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_email.email_fromuser
     *
     * @return the value of t_email.email_fromuser
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public String getEmailFromuser() {
        return emailFromuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_email.email_fromuser
     *
     * @param emailFromuser the value for t_email.email_fromuser
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public void setEmailFromuser(String emailFromuser) {
        this.emailFromuser = emailFromuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_email.create_time
     *
     * @return the value of t_email.create_time
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_email.create_time
     *
     * @param createTime the value for t_email.create_time
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_email.send_time
     *
     * @return the value of t_email.send_time
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_email.send_time
     *
     * @param sendTime the value for t_email.send_time
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_email.email_status
     *
     * @return the value of t_email.email_status
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public Integer getEmailStatus() {
        return emailStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_email.email_status
     *
     * @param emailStatus the value for t_email.email_status
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public void setEmailStatus(Integer emailStatus) {
        this.emailStatus = emailStatus;
    }
}