package com.mds.manager.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EmailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_email
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_email
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_email
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public EmailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_email
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSystemNoIsNull() {
            addCriterion("system_no is null");
            return (Criteria) this;
        }

        public Criteria andSystemNoIsNotNull() {
            addCriterion("system_no is not null");
            return (Criteria) this;
        }

        public Criteria andSystemNoEqualTo(Boolean value) {
            addCriterion("system_no =", value, "systemNo");
            return (Criteria) this;
        }

        public Criteria andSystemNoNotEqualTo(Boolean value) {
            addCriterion("system_no <>", value, "systemNo");
            return (Criteria) this;
        }

        public Criteria andSystemNoGreaterThan(Boolean value) {
            addCriterion("system_no >", value, "systemNo");
            return (Criteria) this;
        }

        public Criteria andSystemNoGreaterThanOrEqualTo(Boolean value) {
            addCriterion("system_no >=", value, "systemNo");
            return (Criteria) this;
        }

        public Criteria andSystemNoLessThan(Boolean value) {
            addCriterion("system_no <", value, "systemNo");
            return (Criteria) this;
        }

        public Criteria andSystemNoLessThanOrEqualTo(Boolean value) {
            addCriterion("system_no <=", value, "systemNo");
            return (Criteria) this;
        }

        public Criteria andSystemNoIn(List<Boolean> values) {
            addCriterion("system_no in", values, "systemNo");
            return (Criteria) this;
        }

        public Criteria andSystemNoNotIn(List<Boolean> values) {
            addCriterion("system_no not in", values, "systemNo");
            return (Criteria) this;
        }

        public Criteria andSystemNoBetween(Boolean value1, Boolean value2) {
            addCriterion("system_no between", value1, value2, "systemNo");
            return (Criteria) this;
        }

        public Criteria andSystemNoNotBetween(Boolean value1, Boolean value2) {
            addCriterion("system_no not between", value1, value2, "systemNo");
            return (Criteria) this;
        }

        public Criteria andEmailNoIsNull() {
            addCriterion("email_no is null");
            return (Criteria) this;
        }

        public Criteria andEmailNoIsNotNull() {
            addCriterion("email_no is not null");
            return (Criteria) this;
        }

        public Criteria andEmailNoEqualTo(String value) {
            addCriterion("email_no =", value, "emailNo");
            return (Criteria) this;
        }

        public Criteria andEmailNoNotEqualTo(String value) {
            addCriterion("email_no <>", value, "emailNo");
            return (Criteria) this;
        }

        public Criteria andEmailNoGreaterThan(String value) {
            addCriterion("email_no >", value, "emailNo");
            return (Criteria) this;
        }

        public Criteria andEmailNoGreaterThanOrEqualTo(String value) {
            addCriterion("email_no >=", value, "emailNo");
            return (Criteria) this;
        }

        public Criteria andEmailNoLessThan(String value) {
            addCriterion("email_no <", value, "emailNo");
            return (Criteria) this;
        }

        public Criteria andEmailNoLessThanOrEqualTo(String value) {
            addCriterion("email_no <=", value, "emailNo");
            return (Criteria) this;
        }

        public Criteria andEmailNoLike(String value) {
            addCriterion("email_no like", value, "emailNo");
            return (Criteria) this;
        }

        public Criteria andEmailNoNotLike(String value) {
            addCriterion("email_no not like", value, "emailNo");
            return (Criteria) this;
        }

        public Criteria andEmailNoIn(List<String> values) {
            addCriterion("email_no in", values, "emailNo");
            return (Criteria) this;
        }

        public Criteria andEmailNoNotIn(List<String> values) {
            addCriterion("email_no not in", values, "emailNo");
            return (Criteria) this;
        }

        public Criteria andEmailNoBetween(String value1, String value2) {
            addCriterion("email_no between", value1, value2, "emailNo");
            return (Criteria) this;
        }

        public Criteria andEmailNoNotBetween(String value1, String value2) {
            addCriterion("email_no not between", value1, value2, "emailNo");
            return (Criteria) this;
        }

        public Criteria andEmailToIsNull() {
            addCriterion("email_to is null");
            return (Criteria) this;
        }

        public Criteria andEmailToIsNotNull() {
            addCriterion("email_to is not null");
            return (Criteria) this;
        }

        public Criteria andEmailToEqualTo(String value) {
            addCriterion("email_to =", value, "emailTo");
            return (Criteria) this;
        }

        public Criteria andEmailToNotEqualTo(String value) {
            addCriterion("email_to <>", value, "emailTo");
            return (Criteria) this;
        }

        public Criteria andEmailToGreaterThan(String value) {
            addCriterion("email_to >", value, "emailTo");
            return (Criteria) this;
        }

        public Criteria andEmailToGreaterThanOrEqualTo(String value) {
            addCriterion("email_to >=", value, "emailTo");
            return (Criteria) this;
        }

        public Criteria andEmailToLessThan(String value) {
            addCriterion("email_to <", value, "emailTo");
            return (Criteria) this;
        }

        public Criteria andEmailToLessThanOrEqualTo(String value) {
            addCriterion("email_to <=", value, "emailTo");
            return (Criteria) this;
        }

        public Criteria andEmailToLike(String value) {
            addCriterion("email_to like", value, "emailTo");
            return (Criteria) this;
        }

        public Criteria andEmailToNotLike(String value) {
            addCriterion("email_to not like", value, "emailTo");
            return (Criteria) this;
        }

        public Criteria andEmailToIn(List<String> values) {
            addCriterion("email_to in", values, "emailTo");
            return (Criteria) this;
        }

        public Criteria andEmailToNotIn(List<String> values) {
            addCriterion("email_to not in", values, "emailTo");
            return (Criteria) this;
        }

        public Criteria andEmailToBetween(String value1, String value2) {
            addCriterion("email_to between", value1, value2, "emailTo");
            return (Criteria) this;
        }

        public Criteria andEmailToNotBetween(String value1, String value2) {
            addCriterion("email_to not between", value1, value2, "emailTo");
            return (Criteria) this;
        }

        public Criteria andEmailTouserIsNull() {
            addCriterion("email_touser is null");
            return (Criteria) this;
        }

        public Criteria andEmailTouserIsNotNull() {
            addCriterion("email_touser is not null");
            return (Criteria) this;
        }

        public Criteria andEmailTouserEqualTo(String value) {
            addCriterion("email_touser =", value, "emailTouser");
            return (Criteria) this;
        }

        public Criteria andEmailTouserNotEqualTo(String value) {
            addCriterion("email_touser <>", value, "emailTouser");
            return (Criteria) this;
        }

        public Criteria andEmailTouserGreaterThan(String value) {
            addCriterion("email_touser >", value, "emailTouser");
            return (Criteria) this;
        }

        public Criteria andEmailTouserGreaterThanOrEqualTo(String value) {
            addCriterion("email_touser >=", value, "emailTouser");
            return (Criteria) this;
        }

        public Criteria andEmailTouserLessThan(String value) {
            addCriterion("email_touser <", value, "emailTouser");
            return (Criteria) this;
        }

        public Criteria andEmailTouserLessThanOrEqualTo(String value) {
            addCriterion("email_touser <=", value, "emailTouser");
            return (Criteria) this;
        }

        public Criteria andEmailTouserLike(String value) {
            addCriterion("email_touser like", value, "emailTouser");
            return (Criteria) this;
        }

        public Criteria andEmailTouserNotLike(String value) {
            addCriterion("email_touser not like", value, "emailTouser");
            return (Criteria) this;
        }

        public Criteria andEmailTouserIn(List<String> values) {
            addCriterion("email_touser in", values, "emailTouser");
            return (Criteria) this;
        }

        public Criteria andEmailTouserNotIn(List<String> values) {
            addCriterion("email_touser not in", values, "emailTouser");
            return (Criteria) this;
        }

        public Criteria andEmailTouserBetween(String value1, String value2) {
            addCriterion("email_touser between", value1, value2, "emailTouser");
            return (Criteria) this;
        }

        public Criteria andEmailTouserNotBetween(String value1, String value2) {
            addCriterion("email_touser not between", value1, value2, "emailTouser");
            return (Criteria) this;
        }

        public Criteria andEmailCarboncopyIsNull() {
            addCriterion("email_carboncopy is null");
            return (Criteria) this;
        }

        public Criteria andEmailCarboncopyIsNotNull() {
            addCriterion("email_carboncopy is not null");
            return (Criteria) this;
        }

        public Criteria andEmailCarboncopyEqualTo(String value) {
            addCriterion("email_carboncopy =", value, "emailCarboncopy");
            return (Criteria) this;
        }

        public Criteria andEmailCarboncopyNotEqualTo(String value) {
            addCriterion("email_carboncopy <>", value, "emailCarboncopy");
            return (Criteria) this;
        }

        public Criteria andEmailCarboncopyGreaterThan(String value) {
            addCriterion("email_carboncopy >", value, "emailCarboncopy");
            return (Criteria) this;
        }

        public Criteria andEmailCarboncopyGreaterThanOrEqualTo(String value) {
            addCriterion("email_carboncopy >=", value, "emailCarboncopy");
            return (Criteria) this;
        }

        public Criteria andEmailCarboncopyLessThan(String value) {
            addCriterion("email_carboncopy <", value, "emailCarboncopy");
            return (Criteria) this;
        }

        public Criteria andEmailCarboncopyLessThanOrEqualTo(String value) {
            addCriterion("email_carboncopy <=", value, "emailCarboncopy");
            return (Criteria) this;
        }

        public Criteria andEmailCarboncopyLike(String value) {
            addCriterion("email_carboncopy like", value, "emailCarboncopy");
            return (Criteria) this;
        }

        public Criteria andEmailCarboncopyNotLike(String value) {
            addCriterion("email_carboncopy not like", value, "emailCarboncopy");
            return (Criteria) this;
        }

        public Criteria andEmailCarboncopyIn(List<String> values) {
            addCriterion("email_carboncopy in", values, "emailCarboncopy");
            return (Criteria) this;
        }

        public Criteria andEmailCarboncopyNotIn(List<String> values) {
            addCriterion("email_carboncopy not in", values, "emailCarboncopy");
            return (Criteria) this;
        }

        public Criteria andEmailCarboncopyBetween(String value1, String value2) {
            addCriterion("email_carboncopy between", value1, value2, "emailCarboncopy");
            return (Criteria) this;
        }

        public Criteria andEmailCarboncopyNotBetween(String value1, String value2) {
            addCriterion("email_carboncopy not between", value1, value2, "emailCarboncopy");
            return (Criteria) this;
        }

        public Criteria andEmailTitleIsNull() {
            addCriterion("email_title is null");
            return (Criteria) this;
        }

        public Criteria andEmailTitleIsNotNull() {
            addCriterion("email_title is not null");
            return (Criteria) this;
        }

        public Criteria andEmailTitleEqualTo(String value) {
            addCriterion("email_title =", value, "emailTitle");
            return (Criteria) this;
        }

        public Criteria andEmailTitleNotEqualTo(String value) {
            addCriterion("email_title <>", value, "emailTitle");
            return (Criteria) this;
        }

        public Criteria andEmailTitleGreaterThan(String value) {
            addCriterion("email_title >", value, "emailTitle");
            return (Criteria) this;
        }

        public Criteria andEmailTitleGreaterThanOrEqualTo(String value) {
            addCriterion("email_title >=", value, "emailTitle");
            return (Criteria) this;
        }

        public Criteria andEmailTitleLessThan(String value) {
            addCriterion("email_title <", value, "emailTitle");
            return (Criteria) this;
        }

        public Criteria andEmailTitleLessThanOrEqualTo(String value) {
            addCriterion("email_title <=", value, "emailTitle");
            return (Criteria) this;
        }

        public Criteria andEmailTitleLike(String value) {
            addCriterion("email_title like", value, "emailTitle");
            return (Criteria) this;
        }

        public Criteria andEmailTitleNotLike(String value) {
            addCriterion("email_title not like", value, "emailTitle");
            return (Criteria) this;
        }

        public Criteria andEmailTitleIn(List<String> values) {
            addCriterion("email_title in", values, "emailTitle");
            return (Criteria) this;
        }

        public Criteria andEmailTitleNotIn(List<String> values) {
            addCriterion("email_title not in", values, "emailTitle");
            return (Criteria) this;
        }

        public Criteria andEmailTitleBetween(String value1, String value2) {
            addCriterion("email_title between", value1, value2, "emailTitle");
            return (Criteria) this;
        }

        public Criteria andEmailTitleNotBetween(String value1, String value2) {
            addCriterion("email_title not between", value1, value2, "emailTitle");
            return (Criteria) this;
        }

        public Criteria andEmailContentIsNull() {
            addCriterion("email_content is null");
            return (Criteria) this;
        }

        public Criteria andEmailContentIsNotNull() {
            addCriterion("email_content is not null");
            return (Criteria) this;
        }

        public Criteria andEmailContentEqualTo(String value) {
            addCriterion("email_content =", value, "emailContent");
            return (Criteria) this;
        }

        public Criteria andEmailContentNotEqualTo(String value) {
            addCriterion("email_content <>", value, "emailContent");
            return (Criteria) this;
        }

        public Criteria andEmailContentGreaterThan(String value) {
            addCriterion("email_content >", value, "emailContent");
            return (Criteria) this;
        }

        public Criteria andEmailContentGreaterThanOrEqualTo(String value) {
            addCriterion("email_content >=", value, "emailContent");
            return (Criteria) this;
        }

        public Criteria andEmailContentLessThan(String value) {
            addCriterion("email_content <", value, "emailContent");
            return (Criteria) this;
        }

        public Criteria andEmailContentLessThanOrEqualTo(String value) {
            addCriterion("email_content <=", value, "emailContent");
            return (Criteria) this;
        }

        public Criteria andEmailContentLike(String value) {
            addCriterion("email_content like", value, "emailContent");
            return (Criteria) this;
        }

        public Criteria andEmailContentNotLike(String value) {
            addCriterion("email_content not like", value, "emailContent");
            return (Criteria) this;
        }

        public Criteria andEmailContentIn(List<String> values) {
            addCriterion("email_content in", values, "emailContent");
            return (Criteria) this;
        }

        public Criteria andEmailContentNotIn(List<String> values) {
            addCriterion("email_content not in", values, "emailContent");
            return (Criteria) this;
        }

        public Criteria andEmailContentBetween(String value1, String value2) {
            addCriterion("email_content between", value1, value2, "emailContent");
            return (Criteria) this;
        }

        public Criteria andEmailContentNotBetween(String value1, String value2) {
            addCriterion("email_content not between", value1, value2, "emailContent");
            return (Criteria) this;
        }

        public Criteria andEmailFromIsNull() {
            addCriterion("email_from is null");
            return (Criteria) this;
        }

        public Criteria andEmailFromIsNotNull() {
            addCriterion("email_from is not null");
            return (Criteria) this;
        }

        public Criteria andEmailFromEqualTo(String value) {
            addCriterion("email_from =", value, "emailFrom");
            return (Criteria) this;
        }

        public Criteria andEmailFromNotEqualTo(String value) {
            addCriterion("email_from <>", value, "emailFrom");
            return (Criteria) this;
        }

        public Criteria andEmailFromGreaterThan(String value) {
            addCriterion("email_from >", value, "emailFrom");
            return (Criteria) this;
        }

        public Criteria andEmailFromGreaterThanOrEqualTo(String value) {
            addCriterion("email_from >=", value, "emailFrom");
            return (Criteria) this;
        }

        public Criteria andEmailFromLessThan(String value) {
            addCriterion("email_from <", value, "emailFrom");
            return (Criteria) this;
        }

        public Criteria andEmailFromLessThanOrEqualTo(String value) {
            addCriterion("email_from <=", value, "emailFrom");
            return (Criteria) this;
        }

        public Criteria andEmailFromLike(String value) {
            addCriterion("email_from like", value, "emailFrom");
            return (Criteria) this;
        }

        public Criteria andEmailFromNotLike(String value) {
            addCriterion("email_from not like", value, "emailFrom");
            return (Criteria) this;
        }

        public Criteria andEmailFromIn(List<String> values) {
            addCriterion("email_from in", values, "emailFrom");
            return (Criteria) this;
        }

        public Criteria andEmailFromNotIn(List<String> values) {
            addCriterion("email_from not in", values, "emailFrom");
            return (Criteria) this;
        }

        public Criteria andEmailFromBetween(String value1, String value2) {
            addCriterion("email_from between", value1, value2, "emailFrom");
            return (Criteria) this;
        }

        public Criteria andEmailFromNotBetween(String value1, String value2) {
            addCriterion("email_from not between", value1, value2, "emailFrom");
            return (Criteria) this;
        }

        public Criteria andEmailFromuserIsNull() {
            addCriterion("email_fromuser is null");
            return (Criteria) this;
        }

        public Criteria andEmailFromuserIsNotNull() {
            addCriterion("email_fromuser is not null");
            return (Criteria) this;
        }

        public Criteria andEmailFromuserEqualTo(String value) {
            addCriterion("email_fromuser =", value, "emailFromuser");
            return (Criteria) this;
        }

        public Criteria andEmailFromuserNotEqualTo(String value) {
            addCriterion("email_fromuser <>", value, "emailFromuser");
            return (Criteria) this;
        }

        public Criteria andEmailFromuserGreaterThan(String value) {
            addCriterion("email_fromuser >", value, "emailFromuser");
            return (Criteria) this;
        }

        public Criteria andEmailFromuserGreaterThanOrEqualTo(String value) {
            addCriterion("email_fromuser >=", value, "emailFromuser");
            return (Criteria) this;
        }

        public Criteria andEmailFromuserLessThan(String value) {
            addCriterion("email_fromuser <", value, "emailFromuser");
            return (Criteria) this;
        }

        public Criteria andEmailFromuserLessThanOrEqualTo(String value) {
            addCriterion("email_fromuser <=", value, "emailFromuser");
            return (Criteria) this;
        }

        public Criteria andEmailFromuserLike(String value) {
            addCriterion("email_fromuser like", value, "emailFromuser");
            return (Criteria) this;
        }

        public Criteria andEmailFromuserNotLike(String value) {
            addCriterion("email_fromuser not like", value, "emailFromuser");
            return (Criteria) this;
        }

        public Criteria andEmailFromuserIn(List<String> values) {
            addCriterion("email_fromuser in", values, "emailFromuser");
            return (Criteria) this;
        }

        public Criteria andEmailFromuserNotIn(List<String> values) {
            addCriterion("email_fromuser not in", values, "emailFromuser");
            return (Criteria) this;
        }

        public Criteria andEmailFromuserBetween(String value1, String value2) {
            addCriterion("email_fromuser between", value1, value2, "emailFromuser");
            return (Criteria) this;
        }

        public Criteria andEmailFromuserNotBetween(String value1, String value2) {
            addCriterion("email_fromuser not between", value1, value2, "emailFromuser");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeIsNull() {
            addCriterion("send_time is null");
            return (Criteria) this;
        }

        public Criteria andSendTimeIsNotNull() {
            addCriterion("send_time is not null");
            return (Criteria) this;
        }

        public Criteria andSendTimeEqualTo(Date value) {
            addCriterion("send_time =", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeNotEqualTo(Date value) {
            addCriterion("send_time <>", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeGreaterThan(Date value) {
            addCriterion("send_time >", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("send_time >=", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeLessThan(Date value) {
            addCriterion("send_time <", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeLessThanOrEqualTo(Date value) {
            addCriterion("send_time <=", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeIn(List<Date> values) {
            addCriterion("send_time in", values, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeNotIn(List<Date> values) {
            addCriterion("send_time not in", values, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeBetween(Date value1, Date value2) {
            addCriterion("send_time between", value1, value2, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeNotBetween(Date value1, Date value2) {
            addCriterion("send_time not between", value1, value2, "sendTime");
            return (Criteria) this;
        }

        public Criteria andEmailStatusIsNull() {
            addCriterion("email_status is null");
            return (Criteria) this;
        }

        public Criteria andEmailStatusIsNotNull() {
            addCriterion("email_status is not null");
            return (Criteria) this;
        }

        public Criteria andEmailStatusEqualTo(Integer value) {
            addCriterion("email_status =", value, "emailStatus");
            return (Criteria) this;
        }

        public Criteria andEmailStatusNotEqualTo(Integer value) {
            addCriterion("email_status <>", value, "emailStatus");
            return (Criteria) this;
        }

        public Criteria andEmailStatusGreaterThan(Integer value) {
            addCriterion("email_status >", value, "emailStatus");
            return (Criteria) this;
        }

        public Criteria andEmailStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("email_status >=", value, "emailStatus");
            return (Criteria) this;
        }

        public Criteria andEmailStatusLessThan(Integer value) {
            addCriterion("email_status <", value, "emailStatus");
            return (Criteria) this;
        }

        public Criteria andEmailStatusLessThanOrEqualTo(Integer value) {
            addCriterion("email_status <=", value, "emailStatus");
            return (Criteria) this;
        }

        public Criteria andEmailStatusIn(List<Integer> values) {
            addCriterion("email_status in", values, "emailStatus");
            return (Criteria) this;
        }

        public Criteria andEmailStatusNotIn(List<Integer> values) {
            addCriterion("email_status not in", values, "emailStatus");
            return (Criteria) this;
        }

        public Criteria andEmailStatusBetween(Integer value1, Integer value2) {
            addCriterion("email_status between", value1, value2, "emailStatus");
            return (Criteria) this;
        }

        public Criteria andEmailStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("email_status not between", value1, value2, "emailStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_email
     *
     * @mbggenerated do_not_delete_during_merge Thu Aug 24 20:09:19 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_email
     *
     * @mbggenerated Thu Aug 24 20:09:19 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}