package com.mds.manager.model;

public class Menu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.id
     *
     * @mbggenerated Fri Aug 18 23:26:18 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.menu_name
     *
     * @mbggenerated Fri Aug 18 23:26:18 CST 2017
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.menu
     *
     * @mbggenerated Fri Aug 18 23:26:18 CST 2017
     */
    private String menu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.parent_menu
     *
     * @mbggenerated Fri Aug 18 23:26:18 CST 2017
     */
    private String parentMenu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.menu_desc
     *
     * @mbggenerated Fri Aug 18 23:26:18 CST 2017
     */
    private String menuDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.menu_icon
     *
     * @mbggenerated Fri Aug 18 23:26:18 CST 2017
     */
    private String menuIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.menu_type
     *
     * @mbggenerated Fri Aug 18 23:26:18 CST 2017
     */
    private Integer menuType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.menu_scope
     *
     * @mbggenerated Fri Aug 18 23:26:18 CST 2017
     */
    private Integer menuScope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.status
     *
     * @mbggenerated Fri Aug 18 23:26:18 CST 2017
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.id
     *
     * @return the value of t_menu.id
     *
     * @mbggenerated Fri Aug 18 23:26:18 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.id
     *
     * @param id the value for t_menu.id
     *
     * @mbggenerated Fri Aug 18 23:26:18 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.menu_name
     *
     * @return the value of t_menu.menu_name
     *
     * @mbggenerated Fri Aug 18 23:26:18 CST 2017
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.menu_name
     *
     * @param menuName the value for t_menu.menu_name
     *
     * @mbggenerated Fri Aug 18 23:26:18 CST 2017
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.menu
     *
     * @return the value of t_menu.menu
     *
     * @mbggenerated Fri Aug 18 23:26:18 CST 2017
     */
    public String getMenu() {
        return menu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.menu
     *
     * @param menu the value for t_menu.menu
     *
     * @mbggenerated Fri Aug 18 23:26:18 CST 2017
     */
    public void setMenu(String menu) {
        this.menu = menu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.parent_menu
     *
     * @return the value of t_menu.parent_menu
     *
     * @mbggenerated Fri Aug 18 23:26:18 CST 2017
     */
    public String getParentMenu() {
        return parentMenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.parent_menu
     *
     * @param parentMenu the value for t_menu.parent_menu
     *
     * @mbggenerated Fri Aug 18 23:26:18 CST 2017
     */
    public void setParentMenu(String parentMenu) {
        this.parentMenu = parentMenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.menu_desc
     *
     * @return the value of t_menu.menu_desc
     *
     * @mbggenerated Fri Aug 18 23:26:18 CST 2017
     */
    public String getMenuDesc() {
        return menuDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.menu_desc
     *
     * @param menuDesc the value for t_menu.menu_desc
     *
     * @mbggenerated Fri Aug 18 23:26:18 CST 2017
     */
    public void setMenuDesc(String menuDesc) {
        this.menuDesc = menuDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.menu_icon
     *
     * @return the value of t_menu.menu_icon
     *
     * @mbggenerated Fri Aug 18 23:26:18 CST 2017
     */
    public String getMenuIcon() {
        return menuIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.menu_icon
     *
     * @param menuIcon the value for t_menu.menu_icon
     *
     * @mbggenerated Fri Aug 18 23:26:18 CST 2017
     */
    public void setMenuIcon(String menuIcon) {
        this.menuIcon = menuIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.menu_type
     *
     * @return the value of t_menu.menu_type
     *
     * @mbggenerated Fri Aug 18 23:26:18 CST 2017
     */
    public Integer getMenuType() {
        return menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.menu_type
     *
     * @param menuType the value for t_menu.menu_type
     *
     * @mbggenerated Fri Aug 18 23:26:18 CST 2017
     */
    public void setMenuType(Integer menuType) {
        this.menuType = menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.menu_scope
     *
     * @return the value of t_menu.menu_scope
     *
     * @mbggenerated Fri Aug 18 23:26:18 CST 2017
     */
    public Integer getMenuScope() {
        return menuScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.menu_scope
     *
     * @param menuScope the value for t_menu.menu_scope
     *
     * @mbggenerated Fri Aug 18 23:26:18 CST 2017
     */
    public void setMenuScope(Integer menuScope) {
        this.menuScope = menuScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.status
     *
     * @return the value of t_menu.status
     *
     * @mbggenerated Fri Aug 18 23:26:18 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.status
     *
     * @param status the value for t_menu.status
     *
     * @mbggenerated Fri Aug 18 23:26:18 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}