package com.mds.manager.model;

import java.util.Date;

public class Notice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.id
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.notice_title
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    private String noticeTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.notice_content
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    private String noticeContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.notice_from
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    private String noticeFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.notice_to
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    private String noticeTo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.status
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.noice_scope
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    private Integer noiceScope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.create_time
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.create_user
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    private String createUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.id
     *
     * @return the value of t_notice.id
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.id
     *
     * @param id the value for t_notice.id
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.notice_title
     *
     * @return the value of t_notice.notice_title
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    public String getNoticeTitle() {
        return noticeTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.notice_title
     *
     * @param noticeTitle the value for t_notice.notice_title
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    public void setNoticeTitle(String noticeTitle) {
        this.noticeTitle = noticeTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.notice_content
     *
     * @return the value of t_notice.notice_content
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    public String getNoticeContent() {
        return noticeContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.notice_content
     *
     * @param noticeContent the value for t_notice.notice_content
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    public void setNoticeContent(String noticeContent) {
        this.noticeContent = noticeContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.notice_from
     *
     * @return the value of t_notice.notice_from
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    public String getNoticeFrom() {
        return noticeFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.notice_from
     *
     * @param noticeFrom the value for t_notice.notice_from
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    public void setNoticeFrom(String noticeFrom) {
        this.noticeFrom = noticeFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.notice_to
     *
     * @return the value of t_notice.notice_to
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    public String getNoticeTo() {
        return noticeTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.notice_to
     *
     * @param noticeTo the value for t_notice.notice_to
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    public void setNoticeTo(String noticeTo) {
        this.noticeTo = noticeTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.status
     *
     * @return the value of t_notice.status
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.status
     *
     * @param status the value for t_notice.status
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.noice_scope
     *
     * @return the value of t_notice.noice_scope
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    public Integer getNoiceScope() {
        return noiceScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.noice_scope
     *
     * @param noiceScope the value for t_notice.noice_scope
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    public void setNoiceScope(Integer noiceScope) {
        this.noiceScope = noiceScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.create_time
     *
     * @return the value of t_notice.create_time
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.create_time
     *
     * @param createTime the value for t_notice.create_time
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.create_user
     *
     * @return the value of t_notice.create_user
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.create_user
     *
     * @param createUser the value for t_notice.create_user
     *
     * @mbggenerated Wed Aug 23 10:28:55 CST 2017
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }
}