package com.mds.manager.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrganizationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_organization
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_organization
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_organization
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    public OrganizationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_organization
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_organization
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrganizationIsNull() {
            addCriterion("organization is null");
            return (Criteria) this;
        }

        public Criteria andOrganizationIsNotNull() {
            addCriterion("organization is not null");
            return (Criteria) this;
        }

        public Criteria andOrganizationEqualTo(String value) {
            addCriterion("organization =", value, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationNotEqualTo(String value) {
            addCriterion("organization <>", value, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationGreaterThan(String value) {
            addCriterion("organization >", value, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationGreaterThanOrEqualTo(String value) {
            addCriterion("organization >=", value, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationLessThan(String value) {
            addCriterion("organization <", value, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationLessThanOrEqualTo(String value) {
            addCriterion("organization <=", value, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationLike(String value) {
            addCriterion("organization like", value, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationNotLike(String value) {
            addCriterion("organization not like", value, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationIn(List<String> values) {
            addCriterion("organization in", values, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationNotIn(List<String> values) {
            addCriterion("organization not in", values, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationBetween(String value1, String value2) {
            addCriterion("organization between", value1, value2, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationNotBetween(String value1, String value2) {
            addCriterion("organization not between", value1, value2, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationParentIsNull() {
            addCriterion("organization_parent is null");
            return (Criteria) this;
        }

        public Criteria andOrganizationParentIsNotNull() {
            addCriterion("organization_parent is not null");
            return (Criteria) this;
        }

        public Criteria andOrganizationParentEqualTo(String value) {
            addCriterion("organization_parent =", value, "organizationParent");
            return (Criteria) this;
        }

        public Criteria andOrganizationParentNotEqualTo(String value) {
            addCriterion("organization_parent <>", value, "organizationParent");
            return (Criteria) this;
        }

        public Criteria andOrganizationParentGreaterThan(String value) {
            addCriterion("organization_parent >", value, "organizationParent");
            return (Criteria) this;
        }

        public Criteria andOrganizationParentGreaterThanOrEqualTo(String value) {
            addCriterion("organization_parent >=", value, "organizationParent");
            return (Criteria) this;
        }

        public Criteria andOrganizationParentLessThan(String value) {
            addCriterion("organization_parent <", value, "organizationParent");
            return (Criteria) this;
        }

        public Criteria andOrganizationParentLessThanOrEqualTo(String value) {
            addCriterion("organization_parent <=", value, "organizationParent");
            return (Criteria) this;
        }

        public Criteria andOrganizationParentLike(String value) {
            addCriterion("organization_parent like", value, "organizationParent");
            return (Criteria) this;
        }

        public Criteria andOrganizationParentNotLike(String value) {
            addCriterion("organization_parent not like", value, "organizationParent");
            return (Criteria) this;
        }

        public Criteria andOrganizationParentIn(List<String> values) {
            addCriterion("organization_parent in", values, "organizationParent");
            return (Criteria) this;
        }

        public Criteria andOrganizationParentNotIn(List<String> values) {
            addCriterion("organization_parent not in", values, "organizationParent");
            return (Criteria) this;
        }

        public Criteria andOrganizationParentBetween(String value1, String value2) {
            addCriterion("organization_parent between", value1, value2, "organizationParent");
            return (Criteria) this;
        }

        public Criteria andOrganizationParentNotBetween(String value1, String value2) {
            addCriterion("organization_parent not between", value1, value2, "organizationParent");
            return (Criteria) this;
        }

        public Criteria andOrganizationNameIsNull() {
            addCriterion("organization_name is null");
            return (Criteria) this;
        }

        public Criteria andOrganizationNameIsNotNull() {
            addCriterion("organization_name is not null");
            return (Criteria) this;
        }

        public Criteria andOrganizationNameEqualTo(String value) {
            addCriterion("organization_name =", value, "organizationName");
            return (Criteria) this;
        }

        public Criteria andOrganizationNameNotEqualTo(String value) {
            addCriterion("organization_name <>", value, "organizationName");
            return (Criteria) this;
        }

        public Criteria andOrganizationNameGreaterThan(String value) {
            addCriterion("organization_name >", value, "organizationName");
            return (Criteria) this;
        }

        public Criteria andOrganizationNameGreaterThanOrEqualTo(String value) {
            addCriterion("organization_name >=", value, "organizationName");
            return (Criteria) this;
        }

        public Criteria andOrganizationNameLessThan(String value) {
            addCriterion("organization_name <", value, "organizationName");
            return (Criteria) this;
        }

        public Criteria andOrganizationNameLessThanOrEqualTo(String value) {
            addCriterion("organization_name <=", value, "organizationName");
            return (Criteria) this;
        }

        public Criteria andOrganizationNameLike(String value) {
            addCriterion("organization_name like", value, "organizationName");
            return (Criteria) this;
        }

        public Criteria andOrganizationNameNotLike(String value) {
            addCriterion("organization_name not like", value, "organizationName");
            return (Criteria) this;
        }

        public Criteria andOrganizationNameIn(List<String> values) {
            addCriterion("organization_name in", values, "organizationName");
            return (Criteria) this;
        }

        public Criteria andOrganizationNameNotIn(List<String> values) {
            addCriterion("organization_name not in", values, "organizationName");
            return (Criteria) this;
        }

        public Criteria andOrganizationNameBetween(String value1, String value2) {
            addCriterion("organization_name between", value1, value2, "organizationName");
            return (Criteria) this;
        }

        public Criteria andOrganizationNameNotBetween(String value1, String value2) {
            addCriterion("organization_name not between", value1, value2, "organizationName");
            return (Criteria) this;
        }

        public Criteria andOrganizationDescIsNull() {
            addCriterion("organization_desc is null");
            return (Criteria) this;
        }

        public Criteria andOrganizationDescIsNotNull() {
            addCriterion("organization_desc is not null");
            return (Criteria) this;
        }

        public Criteria andOrganizationDescEqualTo(String value) {
            addCriterion("organization_desc =", value, "organizationDesc");
            return (Criteria) this;
        }

        public Criteria andOrganizationDescNotEqualTo(String value) {
            addCriterion("organization_desc <>", value, "organizationDesc");
            return (Criteria) this;
        }

        public Criteria andOrganizationDescGreaterThan(String value) {
            addCriterion("organization_desc >", value, "organizationDesc");
            return (Criteria) this;
        }

        public Criteria andOrganizationDescGreaterThanOrEqualTo(String value) {
            addCriterion("organization_desc >=", value, "organizationDesc");
            return (Criteria) this;
        }

        public Criteria andOrganizationDescLessThan(String value) {
            addCriterion("organization_desc <", value, "organizationDesc");
            return (Criteria) this;
        }

        public Criteria andOrganizationDescLessThanOrEqualTo(String value) {
            addCriterion("organization_desc <=", value, "organizationDesc");
            return (Criteria) this;
        }

        public Criteria andOrganizationDescLike(String value) {
            addCriterion("organization_desc like", value, "organizationDesc");
            return (Criteria) this;
        }

        public Criteria andOrganizationDescNotLike(String value) {
            addCriterion("organization_desc not like", value, "organizationDesc");
            return (Criteria) this;
        }

        public Criteria andOrganizationDescIn(List<String> values) {
            addCriterion("organization_desc in", values, "organizationDesc");
            return (Criteria) this;
        }

        public Criteria andOrganizationDescNotIn(List<String> values) {
            addCriterion("organization_desc not in", values, "organizationDesc");
            return (Criteria) this;
        }

        public Criteria andOrganizationDescBetween(String value1, String value2) {
            addCriterion("organization_desc between", value1, value2, "organizationDesc");
            return (Criteria) this;
        }

        public Criteria andOrganizationDescNotBetween(String value1, String value2) {
            addCriterion("organization_desc not between", value1, value2, "organizationDesc");
            return (Criteria) this;
        }

        public Criteria andOrganizationInnerphoneIsNull() {
            addCriterion("organization_innerphone is null");
            return (Criteria) this;
        }

        public Criteria andOrganizationInnerphoneIsNotNull() {
            addCriterion("organization_innerphone is not null");
            return (Criteria) this;
        }

        public Criteria andOrganizationInnerphoneEqualTo(Long value) {
            addCriterion("organization_innerphone =", value, "organizationInnerphone");
            return (Criteria) this;
        }

        public Criteria andOrganizationInnerphoneNotEqualTo(Long value) {
            addCriterion("organization_innerphone <>", value, "organizationInnerphone");
            return (Criteria) this;
        }

        public Criteria andOrganizationInnerphoneGreaterThan(Long value) {
            addCriterion("organization_innerphone >", value, "organizationInnerphone");
            return (Criteria) this;
        }

        public Criteria andOrganizationInnerphoneGreaterThanOrEqualTo(Long value) {
            addCriterion("organization_innerphone >=", value, "organizationInnerphone");
            return (Criteria) this;
        }

        public Criteria andOrganizationInnerphoneLessThan(Long value) {
            addCriterion("organization_innerphone <", value, "organizationInnerphone");
            return (Criteria) this;
        }

        public Criteria andOrganizationInnerphoneLessThanOrEqualTo(Long value) {
            addCriterion("organization_innerphone <=", value, "organizationInnerphone");
            return (Criteria) this;
        }

        public Criteria andOrganizationInnerphoneIn(List<Long> values) {
            addCriterion("organization_innerphone in", values, "organizationInnerphone");
            return (Criteria) this;
        }

        public Criteria andOrganizationInnerphoneNotIn(List<Long> values) {
            addCriterion("organization_innerphone not in", values, "organizationInnerphone");
            return (Criteria) this;
        }

        public Criteria andOrganizationInnerphoneBetween(Long value1, Long value2) {
            addCriterion("organization_innerphone between", value1, value2, "organizationInnerphone");
            return (Criteria) this;
        }

        public Criteria andOrganizationInnerphoneNotBetween(Long value1, Long value2) {
            addCriterion("organization_innerphone not between", value1, value2, "organizationInnerphone");
            return (Criteria) this;
        }

        public Criteria andOrganizationOuterphoneIsNull() {
            addCriterion("organization_outerphone is null");
            return (Criteria) this;
        }

        public Criteria andOrganizationOuterphoneIsNotNull() {
            addCriterion("organization_outerphone is not null");
            return (Criteria) this;
        }

        public Criteria andOrganizationOuterphoneEqualTo(Long value) {
            addCriterion("organization_outerphone =", value, "organizationOuterphone");
            return (Criteria) this;
        }

        public Criteria andOrganizationOuterphoneNotEqualTo(Long value) {
            addCriterion("organization_outerphone <>", value, "organizationOuterphone");
            return (Criteria) this;
        }

        public Criteria andOrganizationOuterphoneGreaterThan(Long value) {
            addCriterion("organization_outerphone >", value, "organizationOuterphone");
            return (Criteria) this;
        }

        public Criteria andOrganizationOuterphoneGreaterThanOrEqualTo(Long value) {
            addCriterion("organization_outerphone >=", value, "organizationOuterphone");
            return (Criteria) this;
        }

        public Criteria andOrganizationOuterphoneLessThan(Long value) {
            addCriterion("organization_outerphone <", value, "organizationOuterphone");
            return (Criteria) this;
        }

        public Criteria andOrganizationOuterphoneLessThanOrEqualTo(Long value) {
            addCriterion("organization_outerphone <=", value, "organizationOuterphone");
            return (Criteria) this;
        }

        public Criteria andOrganizationOuterphoneIn(List<Long> values) {
            addCriterion("organization_outerphone in", values, "organizationOuterphone");
            return (Criteria) this;
        }

        public Criteria andOrganizationOuterphoneNotIn(List<Long> values) {
            addCriterion("organization_outerphone not in", values, "organizationOuterphone");
            return (Criteria) this;
        }

        public Criteria andOrganizationOuterphoneBetween(Long value1, Long value2) {
            addCriterion("organization_outerphone between", value1, value2, "organizationOuterphone");
            return (Criteria) this;
        }

        public Criteria andOrganizationOuterphoneNotBetween(Long value1, Long value2) {
            addCriterion("organization_outerphone not between", value1, value2, "organizationOuterphone");
            return (Criteria) this;
        }

        public Criteria andOrganizationAddressIsNull() {
            addCriterion("organization_address is null");
            return (Criteria) this;
        }

        public Criteria andOrganizationAddressIsNotNull() {
            addCriterion("organization_address is not null");
            return (Criteria) this;
        }

        public Criteria andOrganizationAddressEqualTo(String value) {
            addCriterion("organization_address =", value, "organizationAddress");
            return (Criteria) this;
        }

        public Criteria andOrganizationAddressNotEqualTo(String value) {
            addCriterion("organization_address <>", value, "organizationAddress");
            return (Criteria) this;
        }

        public Criteria andOrganizationAddressGreaterThan(String value) {
            addCriterion("organization_address >", value, "organizationAddress");
            return (Criteria) this;
        }

        public Criteria andOrganizationAddressGreaterThanOrEqualTo(String value) {
            addCriterion("organization_address >=", value, "organizationAddress");
            return (Criteria) this;
        }

        public Criteria andOrganizationAddressLessThan(String value) {
            addCriterion("organization_address <", value, "organizationAddress");
            return (Criteria) this;
        }

        public Criteria andOrganizationAddressLessThanOrEqualTo(String value) {
            addCriterion("organization_address <=", value, "organizationAddress");
            return (Criteria) this;
        }

        public Criteria andOrganizationAddressLike(String value) {
            addCriterion("organization_address like", value, "organizationAddress");
            return (Criteria) this;
        }

        public Criteria andOrganizationAddressNotLike(String value) {
            addCriterion("organization_address not like", value, "organizationAddress");
            return (Criteria) this;
        }

        public Criteria andOrganizationAddressIn(List<String> values) {
            addCriterion("organization_address in", values, "organizationAddress");
            return (Criteria) this;
        }

        public Criteria andOrganizationAddressNotIn(List<String> values) {
            addCriterion("organization_address not in", values, "organizationAddress");
            return (Criteria) this;
        }

        public Criteria andOrganizationAddressBetween(String value1, String value2) {
            addCriterion("organization_address between", value1, value2, "organizationAddress");
            return (Criteria) this;
        }

        public Criteria andOrganizationAddressNotBetween(String value1, String value2) {
            addCriterion("organization_address not between", value1, value2, "organizationAddress");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andOrganizationScopeIsNull() {
            addCriterion("organization_scope is null");
            return (Criteria) this;
        }

        public Criteria andOrganizationScopeIsNotNull() {
            addCriterion("organization_scope is not null");
            return (Criteria) this;
        }

        public Criteria andOrganizationScopeEqualTo(Integer value) {
            addCriterion("organization_scope =", value, "organizationScope");
            return (Criteria) this;
        }

        public Criteria andOrganizationScopeNotEqualTo(Integer value) {
            addCriterion("organization_scope <>", value, "organizationScope");
            return (Criteria) this;
        }

        public Criteria andOrganizationScopeGreaterThan(Integer value) {
            addCriterion("organization_scope >", value, "organizationScope");
            return (Criteria) this;
        }

        public Criteria andOrganizationScopeGreaterThanOrEqualTo(Integer value) {
            addCriterion("organization_scope >=", value, "organizationScope");
            return (Criteria) this;
        }

        public Criteria andOrganizationScopeLessThan(Integer value) {
            addCriterion("organization_scope <", value, "organizationScope");
            return (Criteria) this;
        }

        public Criteria andOrganizationScopeLessThanOrEqualTo(Integer value) {
            addCriterion("organization_scope <=", value, "organizationScope");
            return (Criteria) this;
        }

        public Criteria andOrganizationScopeIn(List<Integer> values) {
            addCriterion("organization_scope in", values, "organizationScope");
            return (Criteria) this;
        }

        public Criteria andOrganizationScopeNotIn(List<Integer> values) {
            addCriterion("organization_scope not in", values, "organizationScope");
            return (Criteria) this;
        }

        public Criteria andOrganizationScopeBetween(Integer value1, Integer value2) {
            addCriterion("organization_scope between", value1, value2, "organizationScope");
            return (Criteria) this;
        }

        public Criteria andOrganizationScopeNotBetween(Integer value1, Integer value2) {
            addCriterion("organization_scope not between", value1, value2, "organizationScope");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_organization
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 21 14:09:37 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_organization
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}