package com.mds.manager.model;

import java.util.Date;

public class Organization {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.id
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.organization
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    private String organization;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.organization_parent
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    private String organizationParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.organization_name
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    private String organizationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.organization_desc
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    private String organizationDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.organization_innerphone
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    private Long organizationInnerphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.organization_outerphone
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    private Long organizationOuterphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.organization_address
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    private String organizationAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.create_time
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.modify_time
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.create_user
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.organization_scope
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    private Integer organizationScope;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.id
     *
     * @return the value of t_organization.id
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.id
     *
     * @param id the value for t_organization.id
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.organization
     *
     * @return the value of t_organization.organization
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    public String getOrganization() {
        return organization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.organization
     *
     * @param organization the value for t_organization.organization
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    public void setOrganization(String organization) {
        this.organization = organization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.organization_parent
     *
     * @return the value of t_organization.organization_parent
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    public String getOrganizationParent() {
        return organizationParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.organization_parent
     *
     * @param organizationParent the value for t_organization.organization_parent
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    public void setOrganizationParent(String organizationParent) {
        this.organizationParent = organizationParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.organization_name
     *
     * @return the value of t_organization.organization_name
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    public String getOrganizationName() {
        return organizationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.organization_name
     *
     * @param organizationName the value for t_organization.organization_name
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    public void setOrganizationName(String organizationName) {
        this.organizationName = organizationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.organization_desc
     *
     * @return the value of t_organization.organization_desc
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    public String getOrganizationDesc() {
        return organizationDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.organization_desc
     *
     * @param organizationDesc the value for t_organization.organization_desc
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    public void setOrganizationDesc(String organizationDesc) {
        this.organizationDesc = organizationDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.organization_innerphone
     *
     * @return the value of t_organization.organization_innerphone
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    public Long getOrganizationInnerphone() {
        return organizationInnerphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.organization_innerphone
     *
     * @param organizationInnerphone the value for t_organization.organization_innerphone
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    public void setOrganizationInnerphone(Long organizationInnerphone) {
        this.organizationInnerphone = organizationInnerphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.organization_outerphone
     *
     * @return the value of t_organization.organization_outerphone
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    public Long getOrganizationOuterphone() {
        return organizationOuterphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.organization_outerphone
     *
     * @param organizationOuterphone the value for t_organization.organization_outerphone
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    public void setOrganizationOuterphone(Long organizationOuterphone) {
        this.organizationOuterphone = organizationOuterphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.organization_address
     *
     * @return the value of t_organization.organization_address
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    public String getOrganizationAddress() {
        return organizationAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.organization_address
     *
     * @param organizationAddress the value for t_organization.organization_address
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    public void setOrganizationAddress(String organizationAddress) {
        this.organizationAddress = organizationAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.create_time
     *
     * @return the value of t_organization.create_time
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.create_time
     *
     * @param createTime the value for t_organization.create_time
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.modify_time
     *
     * @return the value of t_organization.modify_time
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.modify_time
     *
     * @param modifyTime the value for t_organization.modify_time
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.create_user
     *
     * @return the value of t_organization.create_user
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.create_user
     *
     * @param createUser the value for t_organization.create_user
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.organization_scope
     *
     * @return the value of t_organization.organization_scope
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    public Integer getOrganizationScope() {
        return organizationScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.organization_scope
     *
     * @param organizationScope the value for t_organization.organization_scope
     *
     * @mbggenerated Mon Aug 21 14:09:37 CST 2017
     */
    public void setOrganizationScope(Integer organizationScope) {
        this.organizationScope = organizationScope;
    }
}