package com.mds.manager.model;

import java.util.Date;

public class Sms {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms.id
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms.system_no
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    private Integer systemNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms.sms_id
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    private String smsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms.sms_content
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    private String smsContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms.sms_address
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    private String smsAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms.sms_from
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    private String smsFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms.sms_type
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    private Integer smsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms.sms_file
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    private String smsFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms.create_time
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms.send_time
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms.sms_status
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    private Integer smsStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms.sms_service
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    private String smsService;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms.sms_fromuser
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    private String smsFromuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms.sms_addressuser
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    private String smsAddressuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms.id
     *
     * @return the value of t_sms.id
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms.id
     *
     * @param id the value for t_sms.id
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms.system_no
     *
     * @return the value of t_sms.system_no
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public Integer getSystemNo() {
        return systemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms.system_no
     *
     * @param systemNo the value for t_sms.system_no
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public void setSystemNo(Integer systemNo) {
        this.systemNo = systemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms.sms_id
     *
     * @return the value of t_sms.sms_id
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public String getSmsId() {
        return smsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms.sms_id
     *
     * @param smsId the value for t_sms.sms_id
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public void setSmsId(String smsId) {
        this.smsId = smsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms.sms_content
     *
     * @return the value of t_sms.sms_content
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public String getSmsContent() {
        return smsContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms.sms_content
     *
     * @param smsContent the value for t_sms.sms_content
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public void setSmsContent(String smsContent) {
        this.smsContent = smsContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms.sms_address
     *
     * @return the value of t_sms.sms_address
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public String getSmsAddress() {
        return smsAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms.sms_address
     *
     * @param smsAddress the value for t_sms.sms_address
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public void setSmsAddress(String smsAddress) {
        this.smsAddress = smsAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms.sms_from
     *
     * @return the value of t_sms.sms_from
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public String getSmsFrom() {
        return smsFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms.sms_from
     *
     * @param smsFrom the value for t_sms.sms_from
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public void setSmsFrom(String smsFrom) {
        this.smsFrom = smsFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms.sms_type
     *
     * @return the value of t_sms.sms_type
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public Integer getSmsType() {
        return smsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms.sms_type
     *
     * @param smsType the value for t_sms.sms_type
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public void setSmsType(Integer smsType) {
        this.smsType = smsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms.sms_file
     *
     * @return the value of t_sms.sms_file
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public String getSmsFile() {
        return smsFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms.sms_file
     *
     * @param smsFile the value for t_sms.sms_file
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public void setSmsFile(String smsFile) {
        this.smsFile = smsFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms.create_time
     *
     * @return the value of t_sms.create_time
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms.create_time
     *
     * @param createTime the value for t_sms.create_time
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms.send_time
     *
     * @return the value of t_sms.send_time
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms.send_time
     *
     * @param sendTime the value for t_sms.send_time
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms.sms_status
     *
     * @return the value of t_sms.sms_status
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public Integer getSmsStatus() {
        return smsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms.sms_status
     *
     * @param smsStatus the value for t_sms.sms_status
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public void setSmsStatus(Integer smsStatus) {
        this.smsStatus = smsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms.sms_service
     *
     * @return the value of t_sms.sms_service
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public String getSmsService() {
        return smsService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms.sms_service
     *
     * @param smsService the value for t_sms.sms_service
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public void setSmsService(String smsService) {
        this.smsService = smsService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms.sms_fromuser
     *
     * @return the value of t_sms.sms_fromuser
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public String getSmsFromuser() {
        return smsFromuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms.sms_fromuser
     *
     * @param smsFromuser the value for t_sms.sms_fromuser
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public void setSmsFromuser(String smsFromuser) {
        this.smsFromuser = smsFromuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms.sms_addressuser
     *
     * @return the value of t_sms.sms_addressuser
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public String getSmsAddressuser() {
        return smsAddressuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms.sms_addressuser
     *
     * @param smsAddressuser the value for t_sms.sms_addressuser
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public void setSmsAddressuser(String smsAddressuser) {
        this.smsAddressuser = smsAddressuser;
    }
}