package com.mds.manager.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SmsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sms
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sms
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sms
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public SmsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sms
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSystemNoIsNull() {
            addCriterion("system_no is null");
            return (Criteria) this;
        }

        public Criteria andSystemNoIsNotNull() {
            addCriterion("system_no is not null");
            return (Criteria) this;
        }

        public Criteria andSystemNoEqualTo(Integer value) {
            addCriterion("system_no =", value, "systemNo");
            return (Criteria) this;
        }

        public Criteria andSystemNoNotEqualTo(Integer value) {
            addCriterion("system_no <>", value, "systemNo");
            return (Criteria) this;
        }

        public Criteria andSystemNoGreaterThan(Integer value) {
            addCriterion("system_no >", value, "systemNo");
            return (Criteria) this;
        }

        public Criteria andSystemNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("system_no >=", value, "systemNo");
            return (Criteria) this;
        }

        public Criteria andSystemNoLessThan(Integer value) {
            addCriterion("system_no <", value, "systemNo");
            return (Criteria) this;
        }

        public Criteria andSystemNoLessThanOrEqualTo(Integer value) {
            addCriterion("system_no <=", value, "systemNo");
            return (Criteria) this;
        }

        public Criteria andSystemNoIn(List<Integer> values) {
            addCriterion("system_no in", values, "systemNo");
            return (Criteria) this;
        }

        public Criteria andSystemNoNotIn(List<Integer> values) {
            addCriterion("system_no not in", values, "systemNo");
            return (Criteria) this;
        }

        public Criteria andSystemNoBetween(Integer value1, Integer value2) {
            addCriterion("system_no between", value1, value2, "systemNo");
            return (Criteria) this;
        }

        public Criteria andSystemNoNotBetween(Integer value1, Integer value2) {
            addCriterion("system_no not between", value1, value2, "systemNo");
            return (Criteria) this;
        }

        public Criteria andSmsIdIsNull() {
            addCriterion("sms_id is null");
            return (Criteria) this;
        }

        public Criteria andSmsIdIsNotNull() {
            addCriterion("sms_id is not null");
            return (Criteria) this;
        }

        public Criteria andSmsIdEqualTo(String value) {
            addCriterion("sms_id =", value, "smsId");
            return (Criteria) this;
        }

        public Criteria andSmsIdNotEqualTo(String value) {
            addCriterion("sms_id <>", value, "smsId");
            return (Criteria) this;
        }

        public Criteria andSmsIdGreaterThan(String value) {
            addCriterion("sms_id >", value, "smsId");
            return (Criteria) this;
        }

        public Criteria andSmsIdGreaterThanOrEqualTo(String value) {
            addCriterion("sms_id >=", value, "smsId");
            return (Criteria) this;
        }

        public Criteria andSmsIdLessThan(String value) {
            addCriterion("sms_id <", value, "smsId");
            return (Criteria) this;
        }

        public Criteria andSmsIdLessThanOrEqualTo(String value) {
            addCriterion("sms_id <=", value, "smsId");
            return (Criteria) this;
        }

        public Criteria andSmsIdLike(String value) {
            addCriterion("sms_id like", value, "smsId");
            return (Criteria) this;
        }

        public Criteria andSmsIdNotLike(String value) {
            addCriterion("sms_id not like", value, "smsId");
            return (Criteria) this;
        }

        public Criteria andSmsIdIn(List<String> values) {
            addCriterion("sms_id in", values, "smsId");
            return (Criteria) this;
        }

        public Criteria andSmsIdNotIn(List<String> values) {
            addCriterion("sms_id not in", values, "smsId");
            return (Criteria) this;
        }

        public Criteria andSmsIdBetween(String value1, String value2) {
            addCriterion("sms_id between", value1, value2, "smsId");
            return (Criteria) this;
        }

        public Criteria andSmsIdNotBetween(String value1, String value2) {
            addCriterion("sms_id not between", value1, value2, "smsId");
            return (Criteria) this;
        }

        public Criteria andSmsContentIsNull() {
            addCriterion("sms_content is null");
            return (Criteria) this;
        }

        public Criteria andSmsContentIsNotNull() {
            addCriterion("sms_content is not null");
            return (Criteria) this;
        }

        public Criteria andSmsContentEqualTo(String value) {
            addCriterion("sms_content =", value, "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsContentNotEqualTo(String value) {
            addCriterion("sms_content <>", value, "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsContentGreaterThan(String value) {
            addCriterion("sms_content >", value, "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsContentGreaterThanOrEqualTo(String value) {
            addCriterion("sms_content >=", value, "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsContentLessThan(String value) {
            addCriterion("sms_content <", value, "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsContentLessThanOrEqualTo(String value) {
            addCriterion("sms_content <=", value, "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsContentLike(String value) {
            addCriterion("sms_content like", value, "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsContentNotLike(String value) {
            addCriterion("sms_content not like", value, "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsContentIn(List<String> values) {
            addCriterion("sms_content in", values, "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsContentNotIn(List<String> values) {
            addCriterion("sms_content not in", values, "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsContentBetween(String value1, String value2) {
            addCriterion("sms_content between", value1, value2, "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsContentNotBetween(String value1, String value2) {
            addCriterion("sms_content not between", value1, value2, "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsAddressIsNull() {
            addCriterion("sms_address is null");
            return (Criteria) this;
        }

        public Criteria andSmsAddressIsNotNull() {
            addCriterion("sms_address is not null");
            return (Criteria) this;
        }

        public Criteria andSmsAddressEqualTo(String value) {
            addCriterion("sms_address =", value, "smsAddress");
            return (Criteria) this;
        }

        public Criteria andSmsAddressNotEqualTo(String value) {
            addCriterion("sms_address <>", value, "smsAddress");
            return (Criteria) this;
        }

        public Criteria andSmsAddressGreaterThan(String value) {
            addCriterion("sms_address >", value, "smsAddress");
            return (Criteria) this;
        }

        public Criteria andSmsAddressGreaterThanOrEqualTo(String value) {
            addCriterion("sms_address >=", value, "smsAddress");
            return (Criteria) this;
        }

        public Criteria andSmsAddressLessThan(String value) {
            addCriterion("sms_address <", value, "smsAddress");
            return (Criteria) this;
        }

        public Criteria andSmsAddressLessThanOrEqualTo(String value) {
            addCriterion("sms_address <=", value, "smsAddress");
            return (Criteria) this;
        }

        public Criteria andSmsAddressLike(String value) {
            addCriterion("sms_address like", value, "smsAddress");
            return (Criteria) this;
        }

        public Criteria andSmsAddressNotLike(String value) {
            addCriterion("sms_address not like", value, "smsAddress");
            return (Criteria) this;
        }

        public Criteria andSmsAddressIn(List<String> values) {
            addCriterion("sms_address in", values, "smsAddress");
            return (Criteria) this;
        }

        public Criteria andSmsAddressNotIn(List<String> values) {
            addCriterion("sms_address not in", values, "smsAddress");
            return (Criteria) this;
        }

        public Criteria andSmsAddressBetween(String value1, String value2) {
            addCriterion("sms_address between", value1, value2, "smsAddress");
            return (Criteria) this;
        }

        public Criteria andSmsAddressNotBetween(String value1, String value2) {
            addCriterion("sms_address not between", value1, value2, "smsAddress");
            return (Criteria) this;
        }

        public Criteria andSmsFromIsNull() {
            addCriterion("sms_from is null");
            return (Criteria) this;
        }

        public Criteria andSmsFromIsNotNull() {
            addCriterion("sms_from is not null");
            return (Criteria) this;
        }

        public Criteria andSmsFromEqualTo(String value) {
            addCriterion("sms_from =", value, "smsFrom");
            return (Criteria) this;
        }

        public Criteria andSmsFromNotEqualTo(String value) {
            addCriterion("sms_from <>", value, "smsFrom");
            return (Criteria) this;
        }

        public Criteria andSmsFromGreaterThan(String value) {
            addCriterion("sms_from >", value, "smsFrom");
            return (Criteria) this;
        }

        public Criteria andSmsFromGreaterThanOrEqualTo(String value) {
            addCriterion("sms_from >=", value, "smsFrom");
            return (Criteria) this;
        }

        public Criteria andSmsFromLessThan(String value) {
            addCriterion("sms_from <", value, "smsFrom");
            return (Criteria) this;
        }

        public Criteria andSmsFromLessThanOrEqualTo(String value) {
            addCriterion("sms_from <=", value, "smsFrom");
            return (Criteria) this;
        }

        public Criteria andSmsFromLike(String value) {
            addCriterion("sms_from like", value, "smsFrom");
            return (Criteria) this;
        }

        public Criteria andSmsFromNotLike(String value) {
            addCriterion("sms_from not like", value, "smsFrom");
            return (Criteria) this;
        }

        public Criteria andSmsFromIn(List<String> values) {
            addCriterion("sms_from in", values, "smsFrom");
            return (Criteria) this;
        }

        public Criteria andSmsFromNotIn(List<String> values) {
            addCriterion("sms_from not in", values, "smsFrom");
            return (Criteria) this;
        }

        public Criteria andSmsFromBetween(String value1, String value2) {
            addCriterion("sms_from between", value1, value2, "smsFrom");
            return (Criteria) this;
        }

        public Criteria andSmsFromNotBetween(String value1, String value2) {
            addCriterion("sms_from not between", value1, value2, "smsFrom");
            return (Criteria) this;
        }

        public Criteria andSmsTypeIsNull() {
            addCriterion("sms_type is null");
            return (Criteria) this;
        }

        public Criteria andSmsTypeIsNotNull() {
            addCriterion("sms_type is not null");
            return (Criteria) this;
        }

        public Criteria andSmsTypeEqualTo(Integer value) {
            addCriterion("sms_type =", value, "smsType");
            return (Criteria) this;
        }

        public Criteria andSmsTypeNotEqualTo(Integer value) {
            addCriterion("sms_type <>", value, "smsType");
            return (Criteria) this;
        }

        public Criteria andSmsTypeGreaterThan(Integer value) {
            addCriterion("sms_type >", value, "smsType");
            return (Criteria) this;
        }

        public Criteria andSmsTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("sms_type >=", value, "smsType");
            return (Criteria) this;
        }

        public Criteria andSmsTypeLessThan(Integer value) {
            addCriterion("sms_type <", value, "smsType");
            return (Criteria) this;
        }

        public Criteria andSmsTypeLessThanOrEqualTo(Integer value) {
            addCriterion("sms_type <=", value, "smsType");
            return (Criteria) this;
        }

        public Criteria andSmsTypeIn(List<Integer> values) {
            addCriterion("sms_type in", values, "smsType");
            return (Criteria) this;
        }

        public Criteria andSmsTypeNotIn(List<Integer> values) {
            addCriterion("sms_type not in", values, "smsType");
            return (Criteria) this;
        }

        public Criteria andSmsTypeBetween(Integer value1, Integer value2) {
            addCriterion("sms_type between", value1, value2, "smsType");
            return (Criteria) this;
        }

        public Criteria andSmsTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("sms_type not between", value1, value2, "smsType");
            return (Criteria) this;
        }

        public Criteria andSmsFileIsNull() {
            addCriterion("sms_file is null");
            return (Criteria) this;
        }

        public Criteria andSmsFileIsNotNull() {
            addCriterion("sms_file is not null");
            return (Criteria) this;
        }

        public Criteria andSmsFileEqualTo(String value) {
            addCriterion("sms_file =", value, "smsFile");
            return (Criteria) this;
        }

        public Criteria andSmsFileNotEqualTo(String value) {
            addCriterion("sms_file <>", value, "smsFile");
            return (Criteria) this;
        }

        public Criteria andSmsFileGreaterThan(String value) {
            addCriterion("sms_file >", value, "smsFile");
            return (Criteria) this;
        }

        public Criteria andSmsFileGreaterThanOrEqualTo(String value) {
            addCriterion("sms_file >=", value, "smsFile");
            return (Criteria) this;
        }

        public Criteria andSmsFileLessThan(String value) {
            addCriterion("sms_file <", value, "smsFile");
            return (Criteria) this;
        }

        public Criteria andSmsFileLessThanOrEqualTo(String value) {
            addCriterion("sms_file <=", value, "smsFile");
            return (Criteria) this;
        }

        public Criteria andSmsFileLike(String value) {
            addCriterion("sms_file like", value, "smsFile");
            return (Criteria) this;
        }

        public Criteria andSmsFileNotLike(String value) {
            addCriterion("sms_file not like", value, "smsFile");
            return (Criteria) this;
        }

        public Criteria andSmsFileIn(List<String> values) {
            addCriterion("sms_file in", values, "smsFile");
            return (Criteria) this;
        }

        public Criteria andSmsFileNotIn(List<String> values) {
            addCriterion("sms_file not in", values, "smsFile");
            return (Criteria) this;
        }

        public Criteria andSmsFileBetween(String value1, String value2) {
            addCriterion("sms_file between", value1, value2, "smsFile");
            return (Criteria) this;
        }

        public Criteria andSmsFileNotBetween(String value1, String value2) {
            addCriterion("sms_file not between", value1, value2, "smsFile");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeIsNull() {
            addCriterion("send_time is null");
            return (Criteria) this;
        }

        public Criteria andSendTimeIsNotNull() {
            addCriterion("send_time is not null");
            return (Criteria) this;
        }

        public Criteria andSendTimeEqualTo(Date value) {
            addCriterion("send_time =", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeNotEqualTo(Date value) {
            addCriterion("send_time <>", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeGreaterThan(Date value) {
            addCriterion("send_time >", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("send_time >=", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeLessThan(Date value) {
            addCriterion("send_time <", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeLessThanOrEqualTo(Date value) {
            addCriterion("send_time <=", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeIn(List<Date> values) {
            addCriterion("send_time in", values, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeNotIn(List<Date> values) {
            addCriterion("send_time not in", values, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeBetween(Date value1, Date value2) {
            addCriterion("send_time between", value1, value2, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeNotBetween(Date value1, Date value2) {
            addCriterion("send_time not between", value1, value2, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSmsStatusIsNull() {
            addCriterion("sms_status is null");
            return (Criteria) this;
        }

        public Criteria andSmsStatusIsNotNull() {
            addCriterion("sms_status is not null");
            return (Criteria) this;
        }

        public Criteria andSmsStatusEqualTo(Integer value) {
            addCriterion("sms_status =", value, "smsStatus");
            return (Criteria) this;
        }

        public Criteria andSmsStatusNotEqualTo(Integer value) {
            addCriterion("sms_status <>", value, "smsStatus");
            return (Criteria) this;
        }

        public Criteria andSmsStatusGreaterThan(Integer value) {
            addCriterion("sms_status >", value, "smsStatus");
            return (Criteria) this;
        }

        public Criteria andSmsStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("sms_status >=", value, "smsStatus");
            return (Criteria) this;
        }

        public Criteria andSmsStatusLessThan(Integer value) {
            addCriterion("sms_status <", value, "smsStatus");
            return (Criteria) this;
        }

        public Criteria andSmsStatusLessThanOrEqualTo(Integer value) {
            addCriterion("sms_status <=", value, "smsStatus");
            return (Criteria) this;
        }

        public Criteria andSmsStatusIn(List<Integer> values) {
            addCriterion("sms_status in", values, "smsStatus");
            return (Criteria) this;
        }

        public Criteria andSmsStatusNotIn(List<Integer> values) {
            addCriterion("sms_status not in", values, "smsStatus");
            return (Criteria) this;
        }

        public Criteria andSmsStatusBetween(Integer value1, Integer value2) {
            addCriterion("sms_status between", value1, value2, "smsStatus");
            return (Criteria) this;
        }

        public Criteria andSmsStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("sms_status not between", value1, value2, "smsStatus");
            return (Criteria) this;
        }

        public Criteria andSmsServiceIsNull() {
            addCriterion("sms_service is null");
            return (Criteria) this;
        }

        public Criteria andSmsServiceIsNotNull() {
            addCriterion("sms_service is not null");
            return (Criteria) this;
        }

        public Criteria andSmsServiceEqualTo(String value) {
            addCriterion("sms_service =", value, "smsService");
            return (Criteria) this;
        }

        public Criteria andSmsServiceNotEqualTo(String value) {
            addCriterion("sms_service <>", value, "smsService");
            return (Criteria) this;
        }

        public Criteria andSmsServiceGreaterThan(String value) {
            addCriterion("sms_service >", value, "smsService");
            return (Criteria) this;
        }

        public Criteria andSmsServiceGreaterThanOrEqualTo(String value) {
            addCriterion("sms_service >=", value, "smsService");
            return (Criteria) this;
        }

        public Criteria andSmsServiceLessThan(String value) {
            addCriterion("sms_service <", value, "smsService");
            return (Criteria) this;
        }

        public Criteria andSmsServiceLessThanOrEqualTo(String value) {
            addCriterion("sms_service <=", value, "smsService");
            return (Criteria) this;
        }

        public Criteria andSmsServiceLike(String value) {
            addCriterion("sms_service like", value, "smsService");
            return (Criteria) this;
        }

        public Criteria andSmsServiceNotLike(String value) {
            addCriterion("sms_service not like", value, "smsService");
            return (Criteria) this;
        }

        public Criteria andSmsServiceIn(List<String> values) {
            addCriterion("sms_service in", values, "smsService");
            return (Criteria) this;
        }

        public Criteria andSmsServiceNotIn(List<String> values) {
            addCriterion("sms_service not in", values, "smsService");
            return (Criteria) this;
        }

        public Criteria andSmsServiceBetween(String value1, String value2) {
            addCriterion("sms_service between", value1, value2, "smsService");
            return (Criteria) this;
        }

        public Criteria andSmsServiceNotBetween(String value1, String value2) {
            addCriterion("sms_service not between", value1, value2, "smsService");
            return (Criteria) this;
        }

        public Criteria andSmsFromuserIsNull() {
            addCriterion("sms_fromuser is null");
            return (Criteria) this;
        }

        public Criteria andSmsFromuserIsNotNull() {
            addCriterion("sms_fromuser is not null");
            return (Criteria) this;
        }

        public Criteria andSmsFromuserEqualTo(String value) {
            addCriterion("sms_fromuser =", value, "smsFromuser");
            return (Criteria) this;
        }

        public Criteria andSmsFromuserNotEqualTo(String value) {
            addCriterion("sms_fromuser <>", value, "smsFromuser");
            return (Criteria) this;
        }

        public Criteria andSmsFromuserGreaterThan(String value) {
            addCriterion("sms_fromuser >", value, "smsFromuser");
            return (Criteria) this;
        }

        public Criteria andSmsFromuserGreaterThanOrEqualTo(String value) {
            addCriterion("sms_fromuser >=", value, "smsFromuser");
            return (Criteria) this;
        }

        public Criteria andSmsFromuserLessThan(String value) {
            addCriterion("sms_fromuser <", value, "smsFromuser");
            return (Criteria) this;
        }

        public Criteria andSmsFromuserLessThanOrEqualTo(String value) {
            addCriterion("sms_fromuser <=", value, "smsFromuser");
            return (Criteria) this;
        }

        public Criteria andSmsFromuserLike(String value) {
            addCriterion("sms_fromuser like", value, "smsFromuser");
            return (Criteria) this;
        }

        public Criteria andSmsFromuserNotLike(String value) {
            addCriterion("sms_fromuser not like", value, "smsFromuser");
            return (Criteria) this;
        }

        public Criteria andSmsFromuserIn(List<String> values) {
            addCriterion("sms_fromuser in", values, "smsFromuser");
            return (Criteria) this;
        }

        public Criteria andSmsFromuserNotIn(List<String> values) {
            addCriterion("sms_fromuser not in", values, "smsFromuser");
            return (Criteria) this;
        }

        public Criteria andSmsFromuserBetween(String value1, String value2) {
            addCriterion("sms_fromuser between", value1, value2, "smsFromuser");
            return (Criteria) this;
        }

        public Criteria andSmsFromuserNotBetween(String value1, String value2) {
            addCriterion("sms_fromuser not between", value1, value2, "smsFromuser");
            return (Criteria) this;
        }

        public Criteria andSmsAddressuserIsNull() {
            addCriterion("sms_addressuser is null");
            return (Criteria) this;
        }

        public Criteria andSmsAddressuserIsNotNull() {
            addCriterion("sms_addressuser is not null");
            return (Criteria) this;
        }

        public Criteria andSmsAddressuserEqualTo(String value) {
            addCriterion("sms_addressuser =", value, "smsAddressuser");
            return (Criteria) this;
        }

        public Criteria andSmsAddressuserNotEqualTo(String value) {
            addCriterion("sms_addressuser <>", value, "smsAddressuser");
            return (Criteria) this;
        }

        public Criteria andSmsAddressuserGreaterThan(String value) {
            addCriterion("sms_addressuser >", value, "smsAddressuser");
            return (Criteria) this;
        }

        public Criteria andSmsAddressuserGreaterThanOrEqualTo(String value) {
            addCriterion("sms_addressuser >=", value, "smsAddressuser");
            return (Criteria) this;
        }

        public Criteria andSmsAddressuserLessThan(String value) {
            addCriterion("sms_addressuser <", value, "smsAddressuser");
            return (Criteria) this;
        }

        public Criteria andSmsAddressuserLessThanOrEqualTo(String value) {
            addCriterion("sms_addressuser <=", value, "smsAddressuser");
            return (Criteria) this;
        }

        public Criteria andSmsAddressuserLike(String value) {
            addCriterion("sms_addressuser like", value, "smsAddressuser");
            return (Criteria) this;
        }

        public Criteria andSmsAddressuserNotLike(String value) {
            addCriterion("sms_addressuser not like", value, "smsAddressuser");
            return (Criteria) this;
        }

        public Criteria andSmsAddressuserIn(List<String> values) {
            addCriterion("sms_addressuser in", values, "smsAddressuser");
            return (Criteria) this;
        }

        public Criteria andSmsAddressuserNotIn(List<String> values) {
            addCriterion("sms_addressuser not in", values, "smsAddressuser");
            return (Criteria) this;
        }

        public Criteria andSmsAddressuserBetween(String value1, String value2) {
            addCriterion("sms_addressuser between", value1, value2, "smsAddressuser");
            return (Criteria) this;
        }

        public Criteria andSmsAddressuserNotBetween(String value1, String value2) {
            addCriterion("sms_addressuser not between", value1, value2, "smsAddressuser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sms
     *
     * @mbggenerated do_not_delete_during_merge Thu Aug 24 15:07:19 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sms
     *
     * @mbggenerated Thu Aug 24 15:07:19 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}