package com.mds.manager.model;

import java.util.Date;

public class SysResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.id
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.resource_parent
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    private String resourceParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.resource
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    private String resource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.resource_name
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    private String resourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.resource_desc
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    private String resourceDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.resource_type
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    private Integer resourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.resource_scope
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    private Integer resourceScope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.status
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.create_time
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.id
     *
     * @return the value of t_resource.id
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.id
     *
     * @param id the value for t_resource.id
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.resource_parent
     *
     * @return the value of t_resource.resource_parent
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    public String getResourceParent() {
        return resourceParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.resource_parent
     *
     * @param resourceParent the value for t_resource.resource_parent
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    public void setResourceParent(String resourceParent) {
        this.resourceParent = resourceParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.resource
     *
     * @return the value of t_resource.resource
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    public String getResource() {
        return resource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.resource
     *
     * @param resource the value for t_resource.resource
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    public void setResource(String resource) {
        this.resource = resource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.resource_name
     *
     * @return the value of t_resource.resource_name
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.resource_name
     *
     * @param resourceName the value for t_resource.resource_name
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.resource_desc
     *
     * @return the value of t_resource.resource_desc
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    public String getResourceDesc() {
        return resourceDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.resource_desc
     *
     * @param resourceDesc the value for t_resource.resource_desc
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    public void setResourceDesc(String resourceDesc) {
        this.resourceDesc = resourceDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.resource_type
     *
     * @return the value of t_resource.resource_type
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    public Integer getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.resource_type
     *
     * @param resourceType the value for t_resource.resource_type
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    public void setResourceType(Integer resourceType) {
        this.resourceType = resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.resource_scope
     *
     * @return the value of t_resource.resource_scope
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    public Integer getResourceScope() {
        return resourceScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.resource_scope
     *
     * @param resourceScope the value for t_resource.resource_scope
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    public void setResourceScope(Integer resourceScope) {
        this.resourceScope = resourceScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.status
     *
     * @return the value of t_resource.status
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.status
     *
     * @param status the value for t_resource.status
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.create_time
     *
     * @return the value of t_resource.create_time
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.create_time
     *
     * @param createTime the value for t_resource.create_time
     *
     * @mbggenerated Thu Aug 17 18:31:38 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}